server.port: 7071

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/othona
    username: othona
    password: othona
  jpa:
    #    show-sql: true
    open-in-view: false
    generate-ddl: true
  flyway:
    createSchemas: true
    url: jdbc:postgresql://localhost:5432/othona?maxConnections=1&ApplicationName=flyway
    user: othona
    password: othona

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 914286264030-r6r191vlmgoebpdrvticstfgu7dgr6ji.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: 'http://localhost:7071/login/oauth2/code/google'
          facebook:
            client-id: 3332166947110409
            client-secret: 8c8bfd8c71c6714d88dde0d0de57ad8a
            redirect-uri: 'http://localhost:7071/login/oauth2/code/facebook'

logging:
  level:
    root: WARN
    org.stcedd: DEBUG
#    org.springframework.web: debug
#    org.flyway: DEBUG

management:
  server:
    port: 8079
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

