server.port: 7071

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/othona
    username: othona
    password: othona
  jpa:
    #    show-sql: true
    open-in-view: false
    generate-ddl: true
  flyway:
    createSchemas: true
    url: jdbc:postgresql://localhost:5432/othona?maxConnections=1&ApplicationName=flyway
    user: othona
    password: othona

logging:
  level:
    root: WARN
    org.stcedd: DEBUG
#    org.springframework.web: debug
#    org.flyway: DEBUG

management:
  server:
    port: 8079
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

