create table order_entity
(
	id          bigint generated by default as identity
		primary key,
	create_time timestamp,
	created_by  varchar(255),
	update_time timestamp,
	updated_by  varchar(255),
	version     integer          not null,
	adults      integer,
	children    integer,
	email       varchar(255),
	name        varchar(255),
	paid        double precision not null,
	parish      varchar(255),
	telephone   varchar(255),
	total       double precision not null,
	youths      integer
);

alter table order_entity
	owner to othona;
